In [6]:
import numpy as np

In [7]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [17]:
np.ones(10,  dtype=np.int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
np.ones((2, 3),  dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
xx = [0, 1, 1, 1, 0]

In [ ]:
xx